version: '3.4'

networks:
  petbook_network:
    driver: bridge

services:

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    #restart: always
    container_name: PB-controller
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - petbook_network
    ports:
      - "5001:5001"
    env_file:
      - "./db.env"
      - "./apps.env"
      - "./controller/jwt.env"

  redirecter:
    build:
      context: ./redirecter
      dockerfile: Dockerfile
    #restart: always
    container_name: PB-redirecter
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - petbook_network
    ports:
      - "5002:5002"
    env_file:
      - "./db.env"
      - "./apps.env"

  notifier:
    build:
      context: ./notifier
      dockerfile: Dockerfile
    #restart: always
    container_name: PB-notifier
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - petbook_network
    ports:
      - "5003:5003"
    env_file:
      - "./apps.env"
      - "./notifier/jwt.env"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: PB-client
    networks:
      - petbook_network
    ports:
      - "3000:3000"
    env_file:
      - "./apps.env"
    logging:
      #limit logs to 300MB (3 rotations of 100M each)
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"